### ISSUE TITLE
[BUG] [Watchlist Step] Error de ejecución

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#208]
Debería arreglarse solo al arreglar #206 

```
2023-10-16 12:55:43 INFO KafkaConsumer.__init__: Creating KafkaConsumer
2023-10-16 12:55:43 INFO KafkaConsumer.__init__: Creating consumer for b-2.internalstaging.ifh33b.c21.kafka.us-east-1.amazonaws.com:9096,b-1.internalstaging.ifh33b.c21.kafka.us-east-1.amazonaws.com:9096
2023-10-16 12:55:43 INFO KafkaConsumer.__init__: Subscribing to ['^ztf.*']
2023-10-16 12:55:43 INFO WatchlistStep.__init__: Creating WatchlistStep
2023-10-16 12:55:43 INFO KafkaMetricsProducer.__init__: Creating KafkaMetricsProducer
2023-10-16 12:55:43 INFO KafkaMetricsProducer.__init__: Producing metrics to metrics
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/scripts/run_step.py", line 35, in <module>
    step.start()
  File "/app/.venv/lib/python3.8/site-packages/apf/core/step.py", line 191, in start
    self.execute(self.message)
  File "/app/watchlist_step/step.py", line 48, in execute
    raise ValueError(
ValueError: The object has not been inserted in the database yet.                             No further action required.
2023-10-16 12:55:49 INFO KafkaConsumer.__del__: Shutting down Consumer
2023-10-16 12:55:49 INFO KafkaMetricsProducer.__del__: Waiting to produce last messages
```

**Comment by dirodriguezm** [comment]
Efectivamente solucionado al arreglar scribe.
