### ISSUE TITLE
[BUG] [Prv Candidates Step] Can't use schemaless producer

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#296]
**Describe the bug**
Prv Candidates step can't use schemaless producer.

```
pipeline-prv_candidates_step-1  | Traceback (most recent call last):
pipeline-prv_candidates_step-1  |   File "/app/scripts/run_step.py", line 82, in <module>
pipeline-prv_candidates_step-1  |     step_creator().start()
pipeline-prv_candidates_step-1  |   File "/libs/apf/apf/metrics/pyroscope/profile.py", line 16, in pyroscope_context
pipeline-prv_candidates_step-1  |     func(*args, **kwargs)
pipeline-prv_candidates_step-1  |   File "/libs/apf/apf/core/step.py", line 443, in start
pipeline-prv_candidates_step-1  |     self.produce(result)
pipeline-prv_candidates_step-1  |   File "/libs/apf/apf/core/step.py", line 413, in produce
pipeline-prv_candidates_step-1  |     self.producer.produce(prod_message, flush=flush)
pipeline-prv_candidates_step-1  |   File "/libs/apf/apf/producers/kafka.py", line 170, in produce
pipeline-prv_candidates_step-1  |     message = self._serialize_message(message)
pipeline-prv_candidates_step-1  |   File "/libs/apf/apf/producers/kafka.py", line 192, in _serialize_message
pipeline-prv_candidates_step-1  |     fastavro.schemaless_writer(out, self.schema, message, strict=True)
pipeline-prv_candidates_step-1  |   File "fastavro/_write.pyx", line 786, in fastavro._write.schemaless_writer
pipeline-prv_candidates_step-1  |   File "fastavro/_write.pyx", line 450, in fastavro._write.write_data
pipeline-prv_candidates_step-1  |   File "fastavro/_write.pyx", line 394, in fastavro._write.write_record
pipeline-prv_candidates_step-1  |   File "fastavro/_write.pyx", line 444, in fastavro._write.write_data
pipeline-prv_candidates_step-1  |   File "fastavro/_write.pyx", line 180, in fastavro._write.write_array
pipeline-prv_candidates_step-1  |   File "fastavro/_write.pyx", line 450, in fastavro._write.write_data
pipeline-prv_candidates_step-1  |   File "fastavro/_write.pyx", line 358, in fastavro._write.write_record
pipeline-prv_candidates_step-1  | ValueError: record contains more fields than the schema specifies: timestamp

```

**To Reproduce**
1. Create messages with sorting_hat_step using `apf.producers.KafkaSchemalessProducer`
2. Run Prv Candidates Step using `apf.consumers.KafkaSchemalessConsumer` and `apf.producers.KafkaSchemalessProducer`
3. See error

**Expected behavior**
Messages should be produced with schemaless producer.

**Additional context**
The regular `apf.producers.KafkaProducer` works fine.

**Comment by dirodriguezm** [comment]
El error está en que las detecciones al ser consumidas por el `apf.consumer.KafkaConsumer` se le agrega un timestamp. Este timestamp no hace falta enviarlo, por lo que se agregó un método para limpiar cada detección en caso de tener timestamp.

Por otro lado, estaba el mismo problema con detecciones que incluían stamps (incluso stamps null) a pesar que debería haberse hecho un "pop" de ese campo. El error era que se estaba haciendo previo a la generación del modelo de salida.

Finalmente, la explicación de esto es que el `KafkaSchemalessProducer` usa `fastavro.schemaless_writer` que al parecer es más estricto en la verificación de schema que `fastavro.writer`, que permite "enviar" datos adicionales que no están en el esquema, aunque realmente solo produzca lo que si está en el schema.
