### ISSUE TITLE
[Bug] [Lighturve-Step] Error schemaless producer

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#302]
```
Traceback (most recent call last):
  File "/app/scripts/run_step.py", line 80, in <module>
    step_creator().start()
  File "/libs/apf/apf/metrics/pyroscope/profile.py", line 16, in pyroscope_context
    func(*args, **kwargs)
  File "/libs/apf/apf/core/step.py", line 443, in start
    self.produce(result)
  File "/libs/apf/apf/core/step.py", line 413, in produce
    self.producer.produce(prod_message, flush=flush)
  File "/libs/apf/apf/producers/kafka.py", line 174, in produce
    message = self._serialize_message(message)
  File "/libs/apf/apf/producers/kafka.py", line 201, in _serialize_message
    raise e
  File "/libs/apf/apf/producers/kafka.py", line 197, in _serialize_message
    fastavro.schemaless_writer(out, self.schema, message, strict=True)
  File "fastavro/_write.pyx", line 786, in fastavro._write.schemaless_writer
  File "fastavro/_write.pyx", line 450, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 394, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 444, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 180, in fastavro._write.write_array
  File "fastavro/_write.pyx", line 450, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 358, in fastavro._write.write_record
ValueError: record contains more fields than the schema specifies: stellar, e_mag_corr, corrected, mag_corr, e_mag_corr_ext, dubious
```

**Comment by dirodriguezm** [comment]
La solución es eliminar esos campos de las alertas que si lo poseen (porque vienen de BD) en lighturve-step.

La otra opción es filtrarlos en correction-step, pero realmente es mejor dejar que correction los cree nuevamente cuando corresponda.

Nota: Las alertas no corregidas se mantendrán no corregidas. Las nuevas deben pasar por el proceso de corrección y eventualmente tener esos campos.

**Comment by dirodriguezm** [comment]
Se decidió filtrar los campos no necesarios al momento de hacer la query a BD para más eficiencia, en lugar de borrarlos a posteriori en pre_produce.
