### ISSUE TITLE
[Features] Paso de features multistream con ATLAS

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#319]
```
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
warning in stationary: failed to import cython module: falling back to numpy
warning in choleskies: failed to import cython module: falling back to numpy
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'corrected'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/scripts/run_step.py", line 46, in <module>
    step.start()
  File "/libs/apf/apf/metrics/pyroscope/profile.py", line 16, in pyroscope_context
    func(*args, **kwargs)
  File "/libs/apf/apf/core/step.py", line 440, in start
    raise error
  File "/libs/apf/apf/core/step.py", line 436, in start
    result = self.execute(preprocessed_msg)
  File "/app/features/step.py", line 84, in execute
    features_extractor = self.features_extractor(
  File "/app/features/core/ztf.py", line 66, in __init__
    super().__init__(detections, non_detections, xmatches)
  File "/app/features/core/_base.py", line 132, in __init__
    self.detections = DetectionsHandler(
  File "/app/features/core/handlers/_base.py", line 106, in __init__
    self._post_process(alerts=alerts, surveys=surveys, **kwargs)
  File "/app/features/core/handlers/detections.py", line 48, in _post_process
    self._use_corrected()
  File "/app/features/core/handlers/detections.py", line 60, in _use_corrected
    self._alerts["corrected"][idx]
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'corrected'

**Comment by AlxEnashi** [comment]
Se van a crear placeholders de :

- Extractor de features (retorna df vacio)
- Parser de output (retorna lista vacia)
- Parser de scribe (retorna lista vacia)

De atlas.

**Comment by AlxEnashi** [comment]
Cambie el constructor del handler de alertas para tener un early exit si no hay alertas usando una excepcion y atrapo esa excepcion en el step.

El extractor de features va a cambiar, ignacio trabaja en otro asi que complicarme mas la vida es innecesario en mi opinion.
