### ISSUE TITLE
[BUG] [lc-classifier] Error en can_predict

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#381]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/scripts/run_step.py", line 50, in <module>
    step.start()
  File "/libs/apf/apf/metrics/pyroscope/profile.py", line 16, in pyroscope_context
    func(*args, **kwargs)
  File "/libs/apf/apf/core/step.py", line 440, in start
    raise error
  File "/libs/apf/apf/core/step.py", line 436, in start
    result = self.execute(preprocessed_msg)
  File "/app/lc_classification/core/step.py", line 165, in execute
    can, error = self.model.can_predict(model_input)
TypeError: cannot unpack non-iterable numpy.bool_ object

**Comment by dirodriguezm** [comment]
Problema adicional al usar lc_classifier local con dependencias transitivas y las librerias de mhps y P4J. 

Solución: instalar mhps con pip y flag --no-use-pep517 (en progreso)

**Comment by dirodriguezm** [comment]
Can predict tenía una comparación de `tid` por "ztf" cuando el dato era "ZTF".
