### ISSUE TITLE
[BUG] [Correction] Error calculo dubious

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/pipeline#389]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/correction/_step/__init__.py", line 5, in run_step
    CorrectionStep.create_step().start()
  File "/libs/apf/apf/metrics/pyroscope/profile.py", line 16, in pyroscope_context
    func(*args, **kwargs)
  File "/libs/apf/apf/core/step.py", line 440, in start
    raise error
  File "/libs/apf/apf/core/step.py", line 436, in start
    result = self.execute(preprocessed_msg)
  File "/app/correction/_step/step.py", line 115, in execute
    detections = corrector.corrected_as_records()
  File "/app/correction/core/corrector.py", line 120, in corrected_as_records
    corrected = corrected.assign(corrected=self.corrected, dubious=self.dubious, stellar=self.stellar)
  File "/app/correction/core/corrector.py", line 87, in dubious
    return self._apply_all_surveys("is_dubious", default=False, dtype=bool)
  File "/app/correction/core/corrector.py", line 76, in _apply_all_surveys
    basic[mask] = getattr(module, function)(self._detections[mask])
  File "/app/correction/core/strategy/ztf.py", line 29, in is_dubious
    first = is_first_corrected(detections)
  File "/app/correction/core/strategy/ztf.py", line 90, in is_first_corrected
    return corrected[idxmin].set_axis(idxmin.index)
  File "/app/.venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 5074, in set_axis
    return super().set_axis(labels, axis=axis, inplace=inplace, copy=copy)
  File "/app/.venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 808, in set_axis
    return self._set_axis_nocheck(labels, axis, inplace, copy=copy)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 818, in _set_axis_nocheck
    setattr(obj, obj._get_axis_name(axis), labels)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 593, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 230, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/app/.venv/lib/python3.10/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 724563 elements, new values have 4558 elements
```

**Comment by dirodriguezm** [comment]
El PR #390 no soluciona el error. Voy a investigar la causa real y revertir los cambios innecesarios.
